name: wlf
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  persistent_bottom_nav_bar: ^1.5.5
  http: ^0.12.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  cached_network_image: ^2.2.0+1
  flutter_html: ^1.0.0
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/MOCK.json
    - assets/images/

  fonts:

    - family: NHGTX
      fonts:
        - asset: assets/font/NHGTX_bold.ttf
        - asset: assets/font/NHGTX_medium.ttf
        - asset: assets/font/NHGTX_regular.ttf

  uses-material-design: true